---
- name: Desplegar aplicación React
  hosts: localhost
  connection: local
  become: true
  tasks:
    - name: Instalar Nginx localmente en la mv
      package:
        name: nginx
        state: present

    - name: Copiar los archivos construidos a la carpeta de Nginx
      copy:
        src: /sa_practica1_201403517/estatica/index.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: '0644'
    
    - name: Copiar los archivos construidos a la carpeta de Nginx
      copy:
        src: /sa_practica1_201403517/estatica/styles.css
        dest: /var/www/html/styles.css
        owner: root
        group: root
        mode: '0644'
     

    - name: Reiniciar Nginx
      service:
        name: nginx
        state: restarted